steps:
  - label: "Weekly check for updates"
    key: "update"
    command: >
      npm install -g --no-audit npm-check-updates;
      git checkout master && git fetch && git pull --rebase;
      ncu -u;
      npm install --legacy-peer-deps --no-audit;
      npm test;
      git add package.json package-lock.json;
      git commit -m "updating dependencies";
      git push -u origin master;
    soft_fail:
      - exit_status: 1
    agents:
      queue: "node14"
    if: build.source == "schedule"

  - label: "Tests"
    key: "test"
    command:
      - npm install --no-audit
      - npm test
    agents:
      queue: "node14"
    if: build.source != "schedule"

  - label: "Publish Library"
    key: "publish"
    command: >
      git config --global user.email "sdom@involves.com";
      git config --global user.name "Buildkite";
      git checkout master && git fetch && git pull --rebase;
      npm version patch -m "[skip ci] Bumping version";
      git push -u origin master;
      git push -u origin master --tags;
      npm publish;
    agents:
      queue: "node14"
    depends_on:
      - "test"
    if: build.source != "schedule" && build.branch == "master"